# Generated by Django 5.2.9 on 2026-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_image',
            field=models.ImageField(blank=True, help_text='Image to be displayed within the blog body', null=True, upload_to='blog_body_images/'),
        ),
    ]
