# Generated by Django 5.2.9 on 2026-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_body_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_image_2',
            field=models.ImageField(blank=True, help_text='Second image to be displayed within the blog body', null=True, upload_to='blog_body_images/'),
        ),
    ]
